name = "template-blog-webapp-nextjs"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages configuration
[build]
command = "yarn build:cloudflare"
cwd = "."

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT_NAME = "production"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "production"
ENVIRONMENT_NAME = "preview"